# Generated by Django 3.0.7 on 2020-06-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='default.jpg', upload_to='cover_pics'),
        ),
    ]
