# Generated by Django 3.0.7 on 2020-06-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='defaultcover.jpg', upload_to='cover_pics'),
        ),
    ]
